from django.urls import path
from .views import (receive_form_submission,view_leads,Follow_lead,
                    Update_lead_stage,manually_enter_leads,add_follower,
                    get_lead_closure_stats,leads_graph_data,get_new_leads,
                    get_DataSaved_leads,get_successfullyclosed_leads,get_unsuccessfullyclosed_leads,
                    salesmanager_monthly_performance,salesmanger_leads_graph,get_newleads_salesmanager,
                    followed_leads_salesmanager,datasaved_leads_salesmanager,successfully_closed_leads_salesmanager,
                    unsuccessfully_closed_leads_salesmanager,pending_leads_salesmanager,get_pending_leads,
                    get_followedleads_salesmanager,get_unrecorded_salesmanager,salesmanager_crm_performance_graph,
                    salesmanager_crm_graph_Leads,Admin_crm_performance_graph,Admin_crm_graph_Leads,followed_leads_admin,
                    unrecorded_leads_admin,admin_manually_enter_leads,Delete_lead,lead_category_graph,lead_category_current_month)

urlpatterns = [
    path("receive-form/", receive_form_submission, name="receive_form_submission"),
    path("view_leads/",view_leads,name="view-leads"),
    path("takelead/<int:lead_id>/",Follow_lead,name="follow_lead"),
    path("update_stage/<int:lead_id>/",Update_lead_stage,name="update_lead"),
    path("enter_leads/",manually_enter_leads,name="enterleads"),
    path("add_follower/<int:lead_id>/",add_follower,name="add_follower"),
    path("salesmanager_monthly/<int:salesmanager_id>/",get_lead_closure_stats,name="sales_monthly_performance"),
    path('lead_graph/',leads_graph_data,name="lead_graph_data"),
    path('get_new_leads/',get_new_leads,name="get_new_leads"),
    path('get_datasaved_leads/',get_DataSaved_leads,name="datasaved_leads"),
    path('get_successfullyclosed_leads/',get_successfullyclosed_leads,name="successfully_closed_leads"),
    path('get_unsuccessful_leads/',get_unsuccessfullyclosed_leads,name="unsuccessfull_leads"),
    path('salesmanager_monthly_performance/',salesmanager_monthly_performance,name="salesmanager_monthly_performance"),
    path('salesmanager_lead_graph/',salesmanger_leads_graph,name="salesmanger_lead_graph"),
    path('get_new_leads/',get_newleads_salesmanager,name="get_newleads"),
    path('followed_leads/',followed_leads_salesmanager,name="followed_leads"),
    path('datasaved_leads/',datasaved_leads_salesmanager,name="data_saved_leads"),
    path('closed_successfully_leads/',successfully_closed_leads_salesmanager,name="successfully_closed_leads"),
    path('unsuccessfully_closed_leads/',unsuccessfully_closed_leads_salesmanager,name="unsuccessfully_closed_leads"),
    path('pending_leads_salesmanager/',pending_leads_salesmanager,name="pending_leads"),
    path('get_pending_leads/',get_pending_leads,name="pendingLeads"),
    path('get_followed_leads/',get_followedleads_salesmanager,name="followed_leads"),
    path('get_unrecorded_leads/',get_unrecorded_salesmanager,name="get_unrecorded"),
    path('salesmanager_crm_performance/',salesmanager_crm_performance_graph,name="salesmanager_crm_performance"),
    path('salesmanager_lead_graph_total/',salesmanager_crm_graph_Leads,name="salesmanager_leads_graph"),
    path('admin_crm_performance_graph/',Admin_crm_performance_graph,name="admin_crm_performance_graph"),
    path('admin_crm_graph_leads/',Admin_crm_graph_Leads,name="admin_crm_graph_leads"),
    path('admin_followed_lead_list/',followed_leads_admin,name="followed_leads"),
    path('unrecorded_leads_admin/',unrecorded_leads_admin,name="unrecorded_admin_leads"),
    path('admin_manually_enter_lead/',admin_manually_enter_leads,name="admin_manually_enterLead"),
    path('delete_lead/<int:lead_id>/',Delete_lead,name="deleteLead"),
    path('lead_category_graph_admin/',lead_category_graph,name="lead_category_graph"),
    path('lead_category_current_month/',lead_category_current_month,name="lead_category_current_month")
    
]
