# Generated by Django 5.1.6 on 2025-03-29 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=120)),
                ('purpose', models.CharField(max_length=100)),
                ('mode_of_purpose', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=250)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('stage', models.CharField(default='Not Opened', max_length=100)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('follower', models.CharField(default='Nil', max_length=100)),
                ('staff_id', models.IntegerField(default=0)),
            ],
        ),
    ]
