# Generated by Django 5.1.6 on 2025-05-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_category', to='leads_section.leads')),
            ],
        ),
    ]
