# Generated by Django 5.1.6 on 2025-05-05 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_section', '0002_leadcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcategory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
