# Generated by Django 5.1.6 on 2025-03-29 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_section', '0001_initial'),
        ('leads_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phonenumber', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('address', models.CharField(default='Address', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy'), ('for rental', 'For Rental'), ('rental seeker', 'Rental Seeker')], default='sell', max_length=50)),
                ('mode_of_property', models.CharField(choices=[('land', 'Land'), ('house', 'House'), ('flat', 'Flat'), ('office', 'Office'), ('godowns,companies,industries', 'Godowns,Companies,Industries'), ('commerical plots', 'Commercial plots'), ('other', 'Other')], default='house', max_length=100)),
                ('other_mode_of_property', models.CharField(blank=True, max_length=100, null=True)),
                ('demand_price', models.IntegerField()),
                ('location_proposal_district', models.CharField(blank=True, max_length=150, null=True)),
                ('location_proposal_place', models.CharField(blank=True, max_length=150, null=True)),
                ('area_in_sqft', models.CharField(max_length=100)),
                ('building_roof', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_floors', models.IntegerField(blank=True, null=True)),
                ('building_bhk', models.IntegerField(blank=True, null=True)),
                ('additional_note', models.CharField(blank=True, max_length=250, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='databank_photos/')),
                ('location_link', models.URLField(blank=True, max_length=500, null=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_section.sales_manager_reg')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databank_lead', to='leads_section.leads')),
            ],
        ),
    ]
