# Generated by Django 5.1.6 on 2025-04-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databank',
            name='other_mode_of_property',
        ),
        migrations.RemoveField(
            model_name='databank',
            name='pincode',
        ),
    ]
