# Generated by Django 5.1.6 on 2025-04-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0002_remove_databank_other_mode_of_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='mode_of_property',
            field=models.CharField(choices=[('Land', 'land'), ('House', 'house'), ('Flat', 'flat'), ('Office', 'Office'), ('Godowns,Companies,Industries', 'Godowns,Companies,Industries'), ('Commerical plots', 'Commercial plots'), ('Other', 'Other')], default='house', max_length=100),
        ),
        migrations.AlterField(
            model_name='databank',
            name='purpose',
            field=models.CharField(choices=[('For Selling a Property', 'for selling a property'), ('For Buying a Property', 'for buying a property'), ('For Rental or Lease', 'for rental or lease'), ('Looking to rent or Lease a property', 'looking to rent or lease')], max_length=50),
        ),
    ]
