# Generated by Django 5.1.6 on 2025-04-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0003_alter_databank_mode_of_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='purpose',
            field=models.CharField(choices=[('For Selling a Property', 'for selling a property'), ('For Buying a Property', 'for buying a property'), ('For Rental or Lease', 'for rental or lease'), ('Looking to rent or Lease a Property', 'looking to rent or lease')], max_length=50),
        ),
    ]
