# Generated by Django 5.1.6 on 2025-04-02 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0004_alter_databank_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databank',
            name='photos',
        ),
        migrations.CreateModel(
            name='DataBankImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='databank_photos/')),
                ('databank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='databank_section.databank')),
            ],
        ),
    ]
