# Generated by Django 5.1.6 on 2025-04-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0006_alter_databank_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='mode_of_property',
            field=models.CharField(max_length=100),
        ),
    ]
