# Generated by Django 5.1.6 on 2025-05-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0008_alter_databank_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='location_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
