# Generated by Django 5.1.6 on 2025-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0009_alter_databank_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='databank',
            name='lead_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
