# Generated by Django 5.1.6 on 2025-05-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0010_databank_lead_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='lead_category',
            field=models.CharField(default='General Lead', max_length=200),
        ),
    ]
