# Generated by Django 5.1.6 on 2025-05-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0012_alter_databank_lead_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='databank',
            name='image_folder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
