# Generated by Django 5.1.6 on 2025-03-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_event_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True)),
                ('date_time', models.DateTimeField(unique=True)),
                ('priority', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Manager_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True)),
                ('date_time', models.DateTimeField(unique=True)),
                ('priority', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=150)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_section.sales_manager_reg')),
            ],
        ),
    ]
