# Generated by Django 5.1.6 on 2025-03-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_section', '0002_alter_ground_level_managers_reg_joined_by'),
        ('task_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_manager_event',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='sales_manager_event',
            unique_together={('staff', 'date_time')},
        ),
    ]
