# Generated by Django 5.1.6 on 2025-04-11 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_section', '0003_sales_manager_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Event_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200)),
                ('admin_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_section.admin_event_list')),
            ],
        ),
    ]
