# Generated by Django 5.1.6 on 2025-03-29 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databank_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_icon', models.ImageField(null=True, upload_to='project_icons')),
                ('project_name', models.CharField(default='test_project', max_length=200, unique=True)),
                ('importance', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('data_bank', models.ManyToManyField(related_name='projects', to='databank_section.databank')),
            ],
        ),
    ]
