# Generated by Django 5.1.6 on 2025-04-11 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followup_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followup_section.followup')),
            ],
        ),
    ]
